version: '3.8'

services:
  db:
    image: mysql:latest
    container_name: mysql-docker
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sign_up
      MYSQL_USER: root
      MYSQL_PASSWORD: userpassword
    ports:
      - "3310:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - myapp_network

  backend:
    build: ./backend
    container_name: backend-app
    restart: always
    depends_on:
      - db
    environment:
      DATABASE_HOST: db
      DATABASE_USER: myapp_user
      DATABASE_PASSWORD: userpassword
      DATABASE_NAME: myapp_db
    ports:
      - "5000:5000"
    networks:
      - myapp_network

  frontend:
    build: ./frontend
    container_name: frontend-app
    restart: always
    depends_on:
      - backend
    ports:
      - "3000:3000"
    networks:
      - myapp_network

volumes:
  db_data:

networks:
  myapp_network:
